client.secret=15gep9k2scfdaus3njn17lqg34rqcnu3p23u6aqk46nvsktjd933
client.id=1scsm0vn6c3a42btor1f69gv7o
oauthURL=https://mediabacklog-auth.auth.us-east-2.amazoncognito.com/oauth2/token
loginURL=https://mediabacklog-auth.auth.us-east-2.amazoncognito.com/login
redirectURL=https://Media-backlog-env.eba-mubj2ggp.us-east-2.elasticbeanstalk.com/auth
region=us-east-2
poolId=us-east-2_2CKVGahKS