CLIENT_SECRET=15gep9k2scfdaus3njn17lqg34rqcnu3p23u6aqk46nvsktjd933
CLIENT_ID=1scsm0vn6c3a42btor1f69gv7o
OAUTH_URL=https://mediabacklog-auth.auth.us-east-2.amazoncognito.com/oauth2/token
LOGIN_URL=https://mediabacklog-auth.auth.us-east-2.amazoncognito.com/login
REDIRECT_URL=https://mediabacklog-env.eba-xs4nepzw.us-east-2.elasticbeanstalk.com/auth
REGION=us-east-2
POOL_ID=us-east-2_2CKVGahKS