property.filename = logs
appenders = console, infoFile, debugFile, errorFile

# --------------------
# CONSOLE APPENDER
# --------------------
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n


# --------------------
# INFO FILE APPENDER
# --------------------
appender.infoFile.type = File
appender.infoFile.name = INFO_FILE
appender.infoFile.fileName = ${filename}/info.log
appender.infoFile.layout.type = PatternLayout
appender.infoFile.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

appender.infoFile.filter.threshold.type = ThresholdFilter
appender.infoFile.filter.threshold.level = info
appender.infoFile.filter.threshold.onMatch = ACCEPT
appender.infoFile.filter.threshold.onMismatch = DENY


# --------------------
# DEBUG FILE APPENDER
# --------------------
appender.debugFile.type = File
appender.debugFile.name = DEBUG_FILE
appender.debugFile.fileName = ${filename}/debug.log
appender.debugFile.layout.type = PatternLayout
appender.debugFile.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

appender.debugFile.filter.threshold.type = ThresholdFilter
appender.debugFile.filter.threshold.level = debug
appender.debugFile.filter.threshold.onMatch = ACCEPT
appender.debugFile.filter.threshold.onMismatch = DENY


# --------------------
# ERROR FILE APPENDER
# --------------------
appender.errorFile.type = File
appender.errorFile.name = ERROR_FILE
appender.errorFile.fileName = ${filename}/error.log
appender.errorFile.layout.type = PatternLayout
appender.errorFile.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

appender.errorFile.filter.threshold.type = ThresholdFilter
appender.errorFile.filter.threshold.level = error
appender.errorFile.filter.threshold.onMatch = ACCEPT
appender.errorFile.filter.threshold.onMismatch = DENY


# --------------------
# ROOT LOGGER
# --------------------
rootLogger.level = debug
rootLogger.appenderRefs = stdout, infoFile, debugFile, errorFile

rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.infoFile.ref = INFO_FILE
rootLogger.appenderRef.debugFile.ref = DEBUG_FILE
rootLogger.appenderRef.errorFile.ref = ERROR_FILE   